image: Visual Studio 2017
before_build:
  - cmd: nuget restore
build:
  verbosity: minimal
deploy:
  - provider: Environment
    name: PROD
    on:
      branch: master
  - provider: Environment
    name: QA
    on:
      branch: /release\/*/
  - provider: Environment
    name: DEV
    on:
      branch: develop