image: Visual Studio 2017
before_build:
  - cmd: nuget restore
branches:
  only:
    - /feature\/.*/
    - /hotfix\/.*/
build:
  verbosity: minimal
deploy:
  - provider: Environment
    name: DEV
environment:
  environment: FEATURE
