image: Visual Studio 2017
before_build:
  - cmd: nuget restore
branches:
  only:
    - develop
build:
  verbosity: minimal
deploy:
  - provider: Environment
    name: DEV
    on:
      branch: develop
