#version: '1.1.1'
#image: Visual Studio 2017
#before_build:
#  - cmd: nuget restore
#build:
#  verbosity: minimal
-
  branches:
    only:
      - /feature\/.*/
      - /hotfix\/.*/  
  configuration: LOCAL
  deploy:
    - provider: Environment
      name: LOCAL
- 
  branches:
    only:
      - develop 
  before_build:
    - cmd: nuget restore
  deploy:
    - provider: Environment
      name: DEV
  image: Visual Studio 2017
-
  branches:
    only:
      - /release\/.*/

  configuration: QA
  deploy:
    - provider: Environment
      name: QA

-
  branches:
    only:
      - master

  configuration: PROD
  deploy:
    - provider: Environment
      name: PROD

-
  image: Visual Studio 2017
