-
  branches:
    only:
      - /feature\/.*/
      - /hotfix\/.*/ 
  before_build:
    - cmd: nuget restore
    - cmd: npm install -g testery
  deploy:
    - provider: Environment
      name: DEV
- 
  branches:
    only:
      - develop 
  before_build:
    - cmd: nuget restore
    - cmd: npm install -g testery
  after_test:
    - cmd: ls .\Web.Specs\
    - cmd: ls .\Web.Specs\bin\Debug\
    - cmd: echo testery start-session --username="%TESTERY_USERNAME%" --password="%TESTERY_PASSWORD%"
    - cmd: echo testery load-suite --feature-directory=".\Web.Specs\" --suite="SmokeTests"
    - cmd: echo testery upload-specflow-assembly --assembly-id="mysteps" --assembly=".\Web.Specs\bin\Debug\Web.Specs.dll"
    - cmd: echo testery start-testrun --suite="SmokeTests" --output-format="appveyor" --wait
  deploy:
    - provider: Environment
      name: DEV
  environment:
    TESTERY_USERNAME:
      secure: mvVRkzHFDkr8kodPGN8+a5seWh+Uq2nbqycfIWYWSJA=
    TESTERY_PASSWORD:
      secure: CCl2Cjgf5P7PrYzODKIfug==
    ENVIRONMENT:
      secure: QJCXHuY0DfEsQWkH/TXLnw==
    
-
  branches:
    only:
      - /release\/.*/
  before_build:
    - cmd: nuget restore
  deploy:
    - provider: Environment
      name: QA
  environment:
    ENVIRONMENT:
      secure: QJCXHuY0DfEsQWkH/TXLnw==
-
  branches:
    only:
      - master
  before_build:
    - cmd: nuget restore
  after_test:
    - cmd: testery --help
  deploy:
    - provider: Environment
      name: PROD
  environment:
    ENVIRONMENT:
      secure: QJCXHuY0DfEsQWkH/TXLnw==
-
  image: Visual Studio 2017
  version: 1.0.11

  