-
  branches:
    only:
      - /feature\/.*/
      - /hotfix\/.*/ 
  before_build:
    - cmd: nuget restore
  deploy:
    - provider: Environment
      name: DEV
- 
  branches:
    only:
      - develop 
  before_build:
    - cmd: nuget restore
  deploy:
    - provider: Environment
      name: DEV
  environment:
    ENVIRONMENT:
      secure: QJCXHuY0DfEsQWkH/TXLnw==
-
  branches:
    only:
      - /release\/.*/
  before_build:
    - cmd: nuget restore
  deploy:
    - provider: Environment
      name: QA
  environment:
    ENVIRONMENT:
      secure: QJCXHuY0DfEsQWkH/TXLnw==
-
  branches:
    only:
      - master
  before_build:
    - cmd: nuget restore
  deploy:
    - provider: Environment
      name: PROD
  environment:
    ENVIRONMENT:
      secure: QJCXHuY0DfEsQWkH/TXLnw==
-
  image: Visual Studio 2017
  version: 1.0.11
