#version: '1.1.1'
#image: Visual Studio 2017
#before_build:
#  - cmd: nuget restore
#build:
#  verbosity: minimal
-
  branches:
    only:
      - /feature\/.*/
      - /hotfix\/.*/  
  before_build:
    - cmd: nuget restore
  deploy:
    - provider: Environment
      name: LOCAL
- 
  branches:
    only:
      - develop 
  before_build:
    - cmd: nuget restore
  deploy:
    - provider: Environment
      name: DEV
-
  branches:
    only:
      - /release\/.*/
  before_build:
    - cmd: nuget restore
  deploy:
    - provider: Environment
      name: QA

-
  branches:
    only:
      - master
  before_build:
    - cmd: nuget restore
  deploy:
    - provider: Environment
      name: PROD

-
  image: Visual Studio 2017
  version: 1.1.2
